package com.web.pocketbuddy.constants;

public enum ScreenAndPlacements {
    HOME_SCREEN,HOME_SCREEN_BANNER, HOME_SCREEN_STRIP, ACTIVITY_SCREEN, ACTIVITY_SCREEN_BANNER, PROFILE_SCREEN, PROFILE_SCREEN_BANNER, PROFILE_SCREEN_STRIP,
    LOADING_SCREEN, LOADING_SCREEN_BANNER, GROUP_SCREEN, GROUP_DETAILS_SCREEN, GROUP_DETAILS_SCREEN_STRIP
}
